name: cleaneeg
channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10
  - numpy==2.2.6
  - scipy==1.15.2
  - matplotlib==3.10.3
  - pyqt==5.15.11
  - mne==1.5.0
  - mne-icalabel==0.7.0
  - pyprep==0.4.3
  - meegkit==0.1.9
  - pybv==0.7.5
  - h5py==3.13.0
  - pandas==2.3.0
  - pip
  - pip:
    - eeglabio==0.1.0
    - edfio==0.4.9
    - EDFlib-Python==1.0.8
